**Ejercicio 1** Vamos a descargar el stock de Acerinox, S.A de yahoo finance, del cual tendremos que calcular los siguientes datos:

* Descarga los datos de cierre desde el 2007 hasta el 2022 ambos incluidos.

* Realiza un análisis del stock:
    * Habla sobre la tendencia de los retornos

    * Sobre la volatilidad del stock

    * cuál es la perdida/ganancia diaria, semanal y mensual máxima
    

* Max Drawdown calcular y enseñar por pantalla

* Ratio de Sharpe en ventana rollada de 15 dí­as con apply

* Enséñalo por pantalla

--------------------

**WARNING** En caso de no haber obtenido los datos del stock en el apartado anterior se pueden cargar los datos desde el archivo data.csv para poder continuar

------------------------

**Ejercicio 2** Con el anterior stock vamos a realizar 1000 simulaciones a 3 meses (con todos los dí­as de por medio), con el método de montecarlo y de bootstrapping.

* Vamos a obtener las simulaciones cuyos percentiles sean 95 y 99 para ambos métodos

* Compara ambos y di­ cuál es su diferencia.

**Crea un módulo para todas las funciones que utilices.**

**Impórtalo y usa las funciones**

**Ejercicio 3** Dados los stocks AAPL, GLD, MSFT y SPY.

* Descarga los datos desde yahoo finance de todos desde 2015 hasta 2019

* Obten la cartera con el mejor ratio de sharpe usando montecarlo

* Obten la cartera de máxima volatilidad

* Grafica los datos para tener una visión de la frontera

**(Extra)** Calcula la frontera eficiente mediante optimizacion cuadrÃƒÂ¡tica y grafica la soluciÃƒÂ³n junto con los datos anteriores.

**Ejercicio 4** Dados los datos del archivo TTI.csv :

* Calcula la curva de tipos

* Grafícala

* Razona si comprarí­as un bono con precio X con vecimiento Y

**Ejercio 5** Dados los datos del archivo OPT.csv:

* Calcula la volatilidad implicita para todas las fechas.

* Valora los strikes desde X hasta Y para todas las fechas.

* **(Extra)** Muestra un gráfico de la supercicie de volatilidad.

In [ ]:
msft = yf.Ticker("MSFT")
csco = yf.Ticker("CSCO")

# get historical market data
msft_hist = msft.history(period="max")
csco_hist = csco.history(period="max")

csco_hist= csco_hist[csco_hist.index > '2020-01-01']

In [ ]:
csco_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,44.087590,44.417831,43.922468,44.417831,16708100,0.35,0.0
2020-01-03 00:00:00-05:00,43.949986,44.160975,43.555527,43.693130,15577400,0.00,0.0
2020-01-06 00:00:00-05:00,43.243632,43.867426,43.124376,43.849079,22183600,0.00,0.0
2020-01-07 00:00:00-05:00,43.775694,43.775694,43.206937,43.564705,16501900,0.00,0.0
2020-01-08 00:00:00-05:00,43.087681,43.839904,42.940906,43.592220,25175900,0.00,0.0
...,...,...,...,...,...,...,...
2022-10-18 00:00:00-04:00,41.919998,42.220001,41.259998,41.790001,18223300,0.00,0.0
2022-10-19 00:00:00-04:00,41.630001,42.240002,41.470001,41.880001,19071700,0.00,0.0
2022-10-20 00:00:00-04:00,41.560001,42.619999,41.459999,41.709999,16830500,0.00,0.0
2022-10-21 00:00:00-04:00,41.849998,42.970001,41.810001,42.799999,25033700,0.00,0.0
2022-10-24 00:00:00-04:00,43.119999,43.730000,42.900002,43.540001,18783600,0.00,0.0

In [ ]:
# show options expirations
exp_dates = csco.options
print(' Las fechas de vencimiento disponibles son : ', exp_dates)

#elijo, por ejemplo, la fecha de la que está en el noveno lugar
vcto_str = exp_dates[9] 
print('\n La fecha de vencimiento elegida es : ', vcto_str)

 Las fechas de vencimiento disponibles son :  ('2022-10-28', '2022-11-04', '2022-11-11', '2022-11-18', '2022-11-25', '2022-12-02', '2022-12-16', '2023-01-20', '2023-03-17', '2023-04-21', '2023-06-16', '2024-01-19', '2024-06-21', '2025-01-17')

 La fecha de vencimiento elegida es :  2023-04-21

In [ ]:
csco_opt = csco.option_chain(vcto_str)

In [ ]:
# get option chain for specific expiration
csco_opt = csco.option_chain(vcto_str)  

# data available via: opt.calls, opt.puts
csco_opt_calls = csco_opt.calls.loc[:, ['lastTradeDate', 'strike', 'lastPrice']]

#convert lastTradeDate to date format
csco_opt_calls.lastTradeDate = csco_opt_calls.lastTradeDate.apply(lambda x: x.date())



csco_opt_calls

   lastTradeDate  strike  lastPrice
0     2022-08-29    22.5      23.25
1     2022-07-18    27.5      16.15
2     2022-10-13    30.0      10.05
3     2022-10-13    32.5       7.95
4     2022-10-13    35.0       6.20
5     2022-10-13    37.5       5.60
6     2022-10-13    40.0       4.05
7     2022-10-13    42.5       2.74
8     2022-10-13    45.0       1.82
9     2022-10-13    47.5       1.07
10    2022-10-13    50.0       0.64
11    2022-10-13    52.5       0.40
12    2022-10-13    55.0       0.23
13    2022-10-13    57.5       0.13
14    2022-10-12    60.0       0.08
15    2022-10-13    65.0       0.05

In [ ]:
# elijo, por ejemplo, la que está en el séptimo lugar
posicion=7
trade_date = csco_opt_calls.iloc[posicion]['lastTradeDate']
csco_opt_calls = csco_opt_calls[csco_opt_calls['lastTradeDate'] == trade_date]
csco_opt_calls

   lastTradeDate  strike  lastPrice
2     2022-10-13    30.0      10.05
3     2022-10-13    32.5       7.95
4     2022-10-13    35.0       6.20
5     2022-10-13    37.5       5.60
6     2022-10-13    40.0       4.05
7     2022-10-13    42.5       2.74
8     2022-10-13    45.0       1.82
9     2022-10-13    47.5       1.07
10    2022-10-13    50.0       0.64
11    2022-10-13    52.5       0.40
12    2022-10-13    55.0       0.23
13    2022-10-13    57.5       0.13
15    2022-10-13    65.0       0.05

In [ ]:
vcto = datetime.datetime.strptime(vcto_str, '%Y-%m-%d')
T = ((vcto.date()-trade_date).days)/365
S0 = csco_hist.loc[trade_date.strftime('%Y-%m-%d')]['Close']

csco_opt_calls["S0"] = S0
csco_opt_calls["T"] = T

In [ ]:
days = T * 365
vols = []
for i in range(csco_opt_calls.shape[0]):
    K = csco_opt_calls['strike'].iloc[i]
    market_price = csco_opt_calls['lastPrice'].iloc[i]
    c_vol = mibian.BS([S0, K, 0, days], callPrice= market_price)
    vols.append(c_vol.impliedVolatility)
csco_opt_calls["vol"] = vols